route_blocker:
  route_blocker_enabled:
    default: false
    client: true
  route_blocker_block_admins:
    default: false
    hidden: false
  route_blocker_blocked_routes:
    default: ""
    type: list
    client: true
    choices:
      - about
      - site/statistics
